import dr_profile from "../assets/dr_profile.jpg";
import patient_profile from "../assets/patient_profile.png";
export const data = [
  {
    id: 1,
    firstName: "Ziyad",
    lastName: "Elnady",
    specialty: "Pediatric",
    image: dr_profile,
  },
  { id: 2, name: "Ziyad Elnady", job: "Pediatric", prof_img: dr_profile },
];

export const patients = [
  {
    id: 1,
    name: "John Doe",
    age: 30,
    gender: "Male",
    image: patient_profile,
    appointment_date: "January 15",
    appointment_time: "10:00 AM",
    job_title: "Software Engineer",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 28,
    gender: "Female",
    image: patient_profile,
    appointment_date: "February 20",
    appointment_time: "11:30 AM",
    job_title: "Graphic Designer",
  },
  {
    id: 3,
    name: "Alice Johnson",
    age: 35,
    gender: "Female",
    image: patient_profile,
    appointment_date: "March 10",
    appointment_time: "2:00 PM",
    job_title: "Project Manager",
  },
  {
    id: 4,
    name: "Michael Brown",
    age: 40,
    gender: "Male",
    image: patient_profile,
    appointment_date: "April 05",
    appointment_time: "1:00 PM",
    job_title: "Data Analyst",
  },
  {
    id: 5,
    name: "Emily Davis",
    age: 25,
    gender: "Female",
    image: patient_profile,
    appointment_date: "May 18",
    appointment_time: "3:30 PM",
    job_title: "Marketing Specialist",
  },
  {
    id: 6,
    name: "David Wilson",
    age: 50,
    gender: "Male",
    image: patient_profile,
    appointment_date: "June 22",
    appointment_time: "9:15 AM",
    job_title: "Sales Manager",
  },
  {
    id: 7,
    name: "Sophia Martinez",
    age: 32,
    gender: "Female",
    image: patient_profile,
    appointment_date: "July 30",
    appointment_time: "4:45 PM",
    job_title: "Nurse",
  },
];
export const today_patients = [
  {
    id: 1,
    name: "John Doe",
    age: 30,
    gender: "Male",
    image: patient_profile,
    appointment_date: "January 15",
    appointment_time: "10:00 AM",
    job_title: "Software Engineer",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 28,
    gender: "Female",
    image: patient_profile,
    appointment_date: "February 20",
    appointment_time: "11:30 AM",
    job_title: "Graphic Designer",
  },
  {
    id: 3,
    name: "Alice Johnson",
    age: 35,
    gender: "Female",
    image: patient_profile,
    appointment_date: "March 10",
    appointment_time: "2:00 PM",
    job_title: "Project Manager",
  },
  {
    id: 4,
    name: "Michael Brown",
    age: 40,
    gender: "Male",
    image: patient_profile,
    appointment_date: "April 05",
    appointment_time: "1:00 PM",
    job_title: "Data Analyst",
  },
  {
    id: 5,
    name: "Emily Davis",
    age: 25,
    gender: "Female",
    image: patient_profile,
    appointment_date: "May 18",
    appointment_time: "3:30 PM",
    job_title: "Marketing Specialist",
  },
  {
    id: 6,
    name: "David Wilson",
    age: 50,
    gender: "Male",
    image: patient_profile,
    appointment_date: "June 22",
    appointment_time: "9:15 AM",
    job_title: "Sales Manager",
  },
  {
    id: 7,
    name: "Sophia Martinez",
    age: 32,
    gender: "Female",
    image: patient_profile,
    appointment_date: "July 30",
    appointment_time: "4:45 PM",
    job_title: "Nurse",
  },
];
